# Generated by Django 6.0.4 on 2026-04-29 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=35)),
                ("year", models.IntegerField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=60, null=True)),
                ("lineup_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("country_code", models.CharField(blank=True, max_length=8, null=True)),
                ("stage", models.CharField(blank=True, max_length=35, null=True)),
                ("day", models.DateField(blank=True, null=True)),
                ("spotify_link", models.URLField(blank=True, null=True)),
                ("lineup_link", models.URLField(blank=True, null=True)),
                (
                    "festival",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.festival"
                    ),
                ),
            ],
        ),
    ]
