# Generated by Django 6.0.4 on 2026-05-02 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bandentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bandentry',
            constraint=models.UniqueConstraint(fields=('user', 'band'), name='unique_user_band'),
        ),
    ]
